/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiTapeRouteImport } from './routes/api/tape'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiTapeIdRouteImport } from './routes/api/tape.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTapeRoute = ApiTapeRouteImport.update({
  id: '/api/tape',
  path: '/api/tape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTapeIdRoute = ApiTapeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTapeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/tape': typeof ApiTapeRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tape/$id': typeof ApiTapeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/tape': typeof ApiTapeRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tape/$id': typeof ApiTapeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/tape': typeof ApiTapeRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tape/$id': typeof ApiTapeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/api/tape' | '/api/auth/$' | '/api/tape/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/api/tape' | '/api/auth/$' | '/api/tape/$id'
  id:
    '__root__' | '/' | '/login' | '/api/tape' | '/api/auth/$' | '/api/tape/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiTapeRoute: typeof ApiTapeRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tape': {
      id: '/api/tape'
      path: '/api/tape'
      fullPath: '/api/tape'
      preLoaderRoute: typeof ApiTapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tape/$id': {
      id: '/api/tape/$id'
      path: '/$id'
      fullPath: '/api/tape/$id'
      preLoaderRoute: typeof ApiTapeIdRouteImport
      parentRoute: typeof ApiTapeRoute
    }
  }
}

interface ApiTapeRouteChildren {
  ApiTapeIdRoute: typeof ApiTapeIdRoute
}

const ApiTapeRouteChildren: ApiTapeRouteChildren = {
  ApiTapeIdRoute: ApiTapeIdRoute,
}

const ApiTapeRouteWithChildren =
  ApiTapeRoute._addFileChildren(ApiTapeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiTapeRoute: ApiTapeRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
